In [ ]:
import plotly.express as px

In [ ]:
px.data.gapminder()

,country,continent,year,lifeExp,pop,gdpPercap,iso_alpha,iso_num
0,Afghanistan,Asia,1952,28.801,8425333,779.445314,AFG,4
1,Afghanistan,Asia,1957,30.332,9240934,820.853030,AFG,4
2,Afghanistan,Asia,1962,31.997,10267083,853.100710,AFG,4
3,Afghanistan,Asia,1967,34.020,11537966,836.197138,AFG,4
4,Afghanistan,Asia,1972,36.088,13079460,739.981106,AFG,4
...,...,...,...,...,...,...,...,...
1699,Zimbabwe,Africa,1987,62.351,9216418,706.157306,ZWE,716
1700,Zimbabwe,Africa,1992,60.377,10704340,693.420786,ZWE,716
1701,Zimbabwe,Africa,1997,46.809,11404948,792.449960,ZWE,716
1702,Zimbabwe,Africa,2002,39.989,11926563,672.038623,ZWE,716
1703,Zimbabwe,Africa,2007,43.487,12311143,469.709298,ZWE,716

In [ ]:
df = px.data.gapminder().query("country == 'Canada'")

In [ ]:
df.head()

    country continent  year  lifeExp       pop    gdpPercap iso_alpha  iso_num
240  Canada  Americas  1952    68.75  14785584  11367.16112       CAN      124
241  Canada  Americas  1957    69.96  17010154  12489.95006       CAN      124
242  Canada  Americas  1962    71.30  18985849  13462.48555       CAN      124
243  Canada  Americas  1967    72.13  20819767  16076.58803       CAN      124
244  Canada  Americas  1972    72.88  22284500  18970.57086       CAN      124

In [ ]:
fig= px.line(df,x="year",y="lifeExp",title="life expected at canada")
fig.show()

In [ ]:
df= px.data.gapminder().query("continent == 'Oceania'")

In [ ]:
df.head()

,country,continent,year,lifeExp,pop,gdpPercap,iso_alpha,iso_num
60,Australia,Oceania,1952,69.12,8691212,10039.59564,AUS,36
61,Australia,Oceania,1957,70.33,9712569,10949.64959,AUS,36
62,Australia,Oceania,1962,70.93,10794968,12217.22686,AUS,36
63,Australia,Oceania,1967,71.10,11872264,14526.12465,AUS,36
64,Australia,Oceania,1972,71.93,13177000,16788.62948,AUS,36

In [ ]:
df.tail()

,country,continent,year,lifeExp,pop,gdpPercap,iso_alpha,iso_num
1099,New Zealand,Oceania,1987,74.320,3317166,19007.19129,NZL,554
1100,New Zealand,Oceania,1992,76.330,3437674,18363.32494,NZL,554
1101,New Zealand,Oceania,1997,77.550,3676187,21050.41377,NZL,554
1102,New Zealand,Oceania,2002,79.110,3908037,23189.80135,NZL,554
1103,New Zealand,Oceania,2007,80.204,4115771,25185.00911,NZL,554

In [ ]:
fig = px.line(df,x="year",y="lifeExp",color="country")

In [ ]:
fig.show()

In [ ]:
fig = px.line(df,x="year",y="lifeExp",color="country",markers=True)
fig.show()

In [ ]:
data = px.data.stocks()

In [ ]:
data.head()

         date      GOOG      AAPL      AMZN        FB      NFLX      MSFT
0  2018-01-01  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000
1  2018-01-08  1.018172  1.011943  1.061881  0.959968  1.053526  1.015988
2  2018-01-15  1.032008  1.019771  1.053240  0.970243  1.049860  1.020524
3  2018-01-22  1.066783  0.980057  1.140676  1.016858  1.307681  1.066561
4  2018-01-29  1.008773  0.917143  1.163374  1.018357  1.273537  1.040708

In [ ]:
fig = px.line(data,x="GOOG",y="AAPL")
fig.show()

In [ ]:
df = px.data.gapminder().query("country in ['Canada','Botswana']")
df.head()

      country continent  year  lifeExp     pop    gdpPercap iso_alpha  iso_num
156  Botswana    Africa  1952   47.622  442308   851.241141       BWA       72
157  Botswana    Africa  1957   49.618  474639   918.232535       BWA       72
158  Botswana    Africa  1962   51.520  512764   983.653976       BWA       72
159  Botswana    Africa  1967   53.298  553541  1214.709294       BWA       72
160  Botswana    Africa  1972   56.024  619351  2263.611114       BWA       72

In [ ]:
df.head()

      country continent  year  lifeExp     pop    gdpPercap iso_alpha  iso_num
156  Botswana    Africa  1952   47.622  442308   851.241141       BWA       72
157  Botswana    Africa  1957   49.618  474639   918.232535       BWA       72
158  Botswana    Africa  1962   51.520  512764   983.653976       BWA       72
159  Botswana    Africa  1967   53.298  553541  1214.709294       BWA       72
160  Botswana    Africa  1972   56.024  619351  2263.611114       BWA       72

In [ ]:
df.tail()

,country,continent,year,lifeExp,pop,gdpPercap,iso_alpha,iso_num
163,Botswana,Africa,1987,63.622,1151184,6205.883850,BWA,72
164,Botswana,Africa,1992,62.745,1342614,7954.111645,BWA,72
165,Botswana,Africa,1997,52.556,1536536,8647.142313,BWA,72
166,Botswana,Africa,2002,46.634,1630347,11003.605080,BWA,72
167,Botswana,Africa,2007,50.728,1639131,12569.851770,BWA,72

In [ ]:
df["country"].value_counts()

country
Botswana    12
Canada      12
Name: count, dtype: int64

In [ ]:
fig = px.line(df,x="lifeExp",y="gdpPercap",color="country",text="year")
fig.show()